webtalk_init -webtalk_dir C:/Users/dsb21132/Desktop/vhdl-project/thermostat/thermostat.sim/sim_1/behav/xsim/xsim.dir/seg_scanning_display_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sat Mar 18 15:34:39 2023" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2902540" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "176544539_1777485426_210667503_922" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "5e938ea2-9b93-4ab7-a796-b8d6f58f7be5" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "4ca51996935344e19eea88244fc48e45" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "12" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3408 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "10 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.03_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6580_KB" -context "xsim\\usage"
webtalk_transmit -clientid 906446033 -regid "176544539_1777485426_210667503_922" -xml C:/Users/dsb21132/Desktop/vhdl-project/thermostat/thermostat.sim/sim_1/behav/xsim/xsim.dir/seg_scanning_display_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/dsb21132/Desktop/vhdl-project/thermostat/thermostat.sim/sim_1/behav/xsim/xsim.dir/seg_scanning_display_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/dsb21132/Desktop/vhdl-project/thermostat/thermostat.sim/sim_1/behav/xsim/xsim.dir/seg_scanning_display_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
